add_newline = true

format="""\
$time\
$hostname\
$directory\
$package\
$git_branch\
$python\n\
$character\
"""

[time]
disabled = false
format = '[\[$time\]]($style) '

[hostname]
trim_at = '.'
ssh_symbol = ''
format = 'ğŸ–¥ï¸ $hostname($style) '

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = '.../'
